config/routes.rb
Rails.application.routes.draw do
  resources :contests

  root 'welcome#index'

  get     '/',        to: 'welcome#index'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  get     '/logout',  to: 'sessions#delete'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/signin',  to: 'signins#new'
  post    '/signin',  to: 'signins#create'

  get     '/options', to: 'options#index'
  post    '/options', to: 'options#update'

  # This section must be located at the end
  get     '/:url_id', to: 'voices#new'
  get     '/contests/:id/voices', to: 'voices#new_by_id'
  post    '/contests/:id/voices', to: 'voices#create'

  post    '/contests/:id/winner/:winner_audio_id',  to: 'contests#winner'
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :user
  has_many :audios

  attr_accessor :attachment

  validates :name, presence: { message: "El nombre es obligatorio" }
  validates :attachment, presence: { message: "La imagen es obligatoria" }, on: :create
  validate :is_valid_image_file, on: :create
  validate :is_valid_image_file_nil, on: :update
  validates :date_init, presence: { message: "La fecha de inicio es obligatoria" }
  validates :date_end, presence: { message: "La fecha de finalización es obligatoria" }
  validate :date_init_and_date_end
  validates :prize_amount,
            presence: { message: "El monto del premio es obligatorio" },
            numericality: {
                only_integer: { message: "El monto del premio solo acepta números enteros" },
                :allow_nil => false, message: "El monto del premio es obligatorio"
            }
  validates_numericality_of :prize_amount,
                            greater_than: 0,
                            message: "El monto del premio debe ser mayor a $ 0"
  validates_numericality_of :prize_amount,
                            less_than: 10000000000,
                            message: "El monto del premio debe ser menor a $ 10.000.000.000"
  validates :contest_text, presence: { message: "El texto del concurso es obligatorio" }
  validates :recommendations, presence: { message: "Las recomendaciones son obligatorias" }
  validates :url_id,
            presence: { message: "La URL es obligatoria" },
            uniqueness: { message: "La URL ya está asignada a otro concurso" },
            format: { with: /\A[a-zA-Z0-9\-_]+\z/, message: "La URL solo acepta números, letras, _ y -" }

  # Validates that the date_init must be greater than date_end
  def date_init_and_date_end
    if !date_init.blank? && !date_end.blank? && date_init > date_end
      errors.add(:date_init, "La fecha de finalización debe ser mayor o igual a la fecha de inicio")
    end
  end

  def is_valid_image_file_nil
    if !attachment.nil?
      is_valid_image_file
    end
  end

  def is_valid_image_file
    if !FileSystemService.is_valid_image_file(attachment)
      errors.add(:attachment, 'La imagen es inválida, las extensiones aceptadas son: png, jpeg y jpg')
    end
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  layout 'admin'

  # Default values
  @@limits_per_page = Array[5, 10, 20, 30, 40, 50]
  @@limit = @@limits_per_page[5]
  @@offset = 0

  def index
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])

      # The limit and offset values are for pagination
      @limit = params[:limit].nil? ? @@limit : params[:limit]
      @offset = params[:offset].nil? ? @@offset : params[:offset]
      @limits_per_page = @@limits_per_page;

      base_query = Contest.all.where(user_id: session[:current_user_id])

      @contests = base_query
                      .limit(@limit.to_i)
                      .offset(@offset)
                      .order(created_at: :desc)

      quantity_of_pages_needed = (base_query.count.to_f / @limit.to_f).ceil
      calculate_pages(quantity_of_pages_needed)
    else
      redirect_to login_path
    end
  end

  def new
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])
      @contest = Contest.new
    else
      redirect_to login_path
    end
  end

  def create
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])
      @contest = Contest.new(contest_parameters)
      @contest.user = @user
      if !@contest.date_end.nil?
        @contest.date_end = @contest.date_end.change({ hour: 23, min: 59, sec: 59 })
      end
      if @contest.save
        attachment = params[:contest][:attachment]
        save_file(attachment)

        @contest.update_attribute(:url, get_host + params[:contest][:url_id])
        redirect_to @contest
      else
        render 'new'
      end
    else
      redirect_to login_path
    end
  end

  def show
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])

      if Contest.exists?(params[:id])
        @contest = Contest.find(params[:id])
        # The limit and offset values are for pagination
        @limit = params[:limit].nil? ? @@limit : params[:limit]
        @offset = params[:offset].nil? ? @@offset : params[:offset]
        @limits_per_page = @@limits_per_page;

        @audios = @contest.audios
                        .limit(@limit.to_i)
                        .offset(@offset)
                        .order(created_at: :desc)

        quantity_of_pages_needed = (@contest.audios.count.to_f / @limit.to_f).ceil
        calculate_pages(quantity_of_pages_needed)
      else
        render_page_not_found
      end
    else
      redirect_to login_path
    end
  end

  def edit
    if session[:current_user_id]
      @user = User.find(session[:current_user_id])
      @contest = Contest.find(params[:id])
    else
      redirect_to login_path
    end
  end

  def update
    @user = User.find(session[:current_user_id])
    @contest = Contest.find(params[:id])
    if @contest.update(contest_parameters)
      @contest.update_attribute(:date_end, @contest.date_end.change({ hour: 23, min: 59, sec: 59 }))
      # If there was a new image selected, then update the new one
      attachment = params[:contest][:attachment]
      if !attachment.nil?
        save_file(attachment)
      end

      @contest.update_attribute(:url, get_host + params[:contest][:url_id])
      redirect_to @contest
    else
      render 'edit'
    end
  end

  def destroy
    @contest = Contest.find(params[:id])
    # Delete the audios too
    @contest.audios.each do |audio|
      audio.destroy
      FileSystemService.delete(audio.location_original_audio)
      if !audio.location_converted_audio.nil?
        FileSystemService.delete(audio.location_converted_audio)
      end
    end
    @contest.destroy
    redirect_to contests_path
  end

  def winner
    @contest = Contest.find(params[:id])
    audio = Audio.find(params[:winner_audio_id])

    @contest.update_attribute(:winner_audio_id, audio.id)
    redirect_to @contest
  end

  private def contest_parameters
    params.require(:contest).permit(:name, :date_init, :date_end, :prize_amount, :contest_text, :recommendations, :attachment, :url_id)
  end

  def get_host
    ENV.fetch("CONTESTS_SERVER_URL")
  end

  def get_nice_download_filename(audio, original)
    extension = File.extname(audio.original_name)
    if !original
      extension = File.extname(audio.converted_name)
    end

    audio.participant.first_name + ' concurso ' + audio.contest.id.to_s + extension
  end

  private def calculate_pages(quantity_of_pages_needed)
    @pages = Array[]
    page = 1
    while quantity_of_pages_needed >= page
      @pages.push(page)
      page += 1
    end

    if quantity_of_pages_needed == 1
      @pages = Array[]
    end

    @current_page = (@offset.to_f / @limit.to_f).round + 1
  end

  # Save image in file system and update values in database
  private def save_file(attachment)
    extension = File.extname(attachment.original_filename)

    # Generate the file name with the extension
    file_name = @contest.id.to_s + "_" + Time.now.to_i.to_s + extension
    images_folder = ENV.fetch("CONTESTS_PATH_IMAGES").to_s + '/'

    # Save image in file system
    path = FileSystemService.save(attachment, file_name, images_folder)

    # Update values in database
    @contest.update_attribute(:banner_image_name, file_name)
    @contest.update_attribute(:location_banner_image, path)
  end

  def get_winner(contest)
    if contest.winner_audio_id.nil?
      return "Aún no hay un ganador"
    else
      audio = Audio.find(contest.winner_audio_id)
      return "Audio # " + audio.id.to_s + " enviado por " + audio.participant.first_name + " " + audio.participant.last_name
    end
  end

  helper_method :get_host
  helper_method :get_nice_download_filename
  helper_method :get_winner
end

app/views/contests/edit.html.erb
<div class="row">
  <div class="card shadow mb-4 w-100">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Editar concurso</h6>
    </div>
    <div class="card-body">
      <%= form_with scope: :contest, url: contest_path, method: :put, local: true do |form| %>
        <div class="form-group error-div">
          <% if @contest.errors.any? %>
            <div class="col-sm-12 mb-3 mb-sm-0">
              <p>
                Hay <%= @contest.errors.count %> <%= @contest.errors.count.equal?(1) ? "error" : "errores" %>
                en el formulario:
              </p>
              <ul>
                <% @contest.errors.messages.each do |attr, msg| %>
                  <% msg.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>ID</label>
            <%= form.text_field :name, class: "form-control", "disabled": "disabled", value: @contest.id %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>* Nombre</label>
            <%= form.text_field :name, class: "form-control", placeholder: "Digita el nombre del concurso" %>
          </div>
          <div class="col-sm-3 mb-3 mb-sm-0">
            <label>Imagen</label>
            <%= form.file_field :attachment, class: "form-control border-0" %>
          </div>
          <div class="col-sm-3 mb-3 mb-sm-0">
            <%= link_to '', "#", "data-toggle": "modal", "data-target": "#imageModal", class: "btn btn-circle fas fa-image btn-primary form-control" %>
            <label>Ver imagen actual</label>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>* Fecha de inicio</label>
            <div class="input-group">
              <%= form.date_field :date_init, class: "form-control", 'aria-describedby' => 'date_init-addon' %>
              <div class="input-group-append">
                <span class="input-group-text" id="date_init_addon">12:00:00 a.m.</span>
              </div>
            </div>
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>* Fecha de finalización</label>
            <div class="input-group">
              <%= form.date_field :date_end, class: "form-control", 'aria-describedby' => 'date_end-addon' %>
              <div class="input-group-append">
                <span class="input-group-text" id="date_end-addon">11:59:59 p.m.</span>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>* Monto del premio</label>
            <%= form.number_field :prize_amount, class: "form-control", placeholder: "Cantidad monetaria que recibe el ganador" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <label>* Texto</label>
            <%= form.text_area :contest_text, class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <label>* Recomendaciones</label>
            <%= form.text_area :recommendations, class: "form-control" %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <label>* URL</label>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="url-addon"><%= get_host %></span>
              </div>
              <%= form.text_field :url_id, class: "form-control", 'aria-describedby' => 'url-addon' %>
            </div>
          </div>
        </div>
        <div class="form-group row error-div text-right">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <p>* Campos obligatorios</p>
          </div>
        </div>
        <div class="form-group row text-right">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <%= form.submit 'Editar concurso', class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Image modal -->
<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= @contest.name %></h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <img alt="<%= @contest.name %>" src="<%= image_path(@contest.banner_image_name) %>" style="max-width: 100%; height: 400px;"/>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/contests/index.html.erb
<div class="row">
  <div class="card shadow mb-4 w-100">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Concursos</h6>
    </div>
    <% if !@contests.blank? %>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered small" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Fecha de inicio</th>
              <th>Fecha de finalización</th>
              <th>Premio</th>
              <th>Fecha de creación</th>
              <th>Voces registradas</th>
              <th>URL</th>
              <th>Ver</th>
              <th>Editar</th>
              <th>Borrar</th>
            </tr>
            </thead>
            <tbody>
            <% @contests.each do |contest| %>
              <tr>
                <td><%= contest.id %></td>
                <td><%= contest.name %></td>
                <td><%= l contest.date_init, format: "%d de %B de %Y a la(s) %I:%M %P %Z" %></td>
                <td><%= l contest.date_end, format: "%d de %B de %Y a la(s) %I:%M %P %Z" %></td>
                <td><%= number_to_currency(contest.prize_amount) %></td>
                <td><%= l DateService.get_created_at_COT(contest.created_at), format: "%d de %B de %Y a la(s) %I:%M %P COT" %></td>
                <td><%= contest.audios.count %></td>
                <td><%= link_to contest.url, contest.url, target: '_blank' %></td>
                <td>
                  <%= link_to 'Ver', contest_path(contest), class: "btn btn-primary" %>
                </td>
                <td>
                  <%= link_to 'Editar', edit_contest_path(contest), class: "btn btn-secondary" %></td>
                <td>
                  <%= link_to 'Eliminar', "#", "data-toggle": "modal", "data-target": "#deleteModal" + contest.id.to_s, class: "btn btn-danger" %>
                  <!-- Delete modal -->
                  <div class="modal fade" id="deleteModal<%= contest.id %>" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Eliminar concurso "<%= contest.name %>"</h5>
                          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <% if contest.audios.blank? %>
                            Este concurso NO tiene audios registrados y se podría eliminar sin problemas
                          <% else %>
                            Este concurso tiene <%= contest.audios.count %> audio(s) registrado(s) ¿Deseas eliminarlo de todas formas?
                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                          <%= form_with url: contest_path(contest), method: :delete do |form| %>
                            <%= form.submit 'Eliminar', class: "btn btn-primary" %>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan="11">
                <select id="selectOpt" onchange="getContests()" class="text-left">
                  <% @limits_per_page.each do |limit| %>
                    <% if limit.to_s == @limit.to_s %>
                      <option value="<%= limit %>" selected><%= limit %></option>
                    <% else %>
                      <option value="<%= limit %>"><%= limit %></option>
                    <% end %>
                  <% end %>
                </select>
                &nbsp;
                registros por página
                <nav class="text-right float-right">
                  <ul class="pagination">
                    <% @pages.each do |page| %>
                      <li class="page-item">
                        <% if page.to_s == @current_page.to_s %>
                          <a class="page-link"><%= page %></a>
                        <% else %>
                          <%= link_to page.to_s, contests_path + '?offset=' + ((page - 1) * @limit.to_i).to_s + '&limit=' + @limit.to_s, class: "page-link" %>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </nav>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <div class="card-body">
        <p class="mb-4">Aún no tienes concursos registrados</p>
        <p class="mb-4"><%= link_to 'Empieza registrando un nuevo concurso !!!', new_contest_path %></p>
      </div>
    <% end %>
  </div>
</div>

<script>
  function getContests() {
    let myselect = document.getElementById("selectOpt");
    window.location.href = '<%= contests_path %>?limit='
        + myselect.options[myselect.selectedIndex].value;
  }
</script>

app/views/contests/show.html.erb
<div class="row">
  <div class="card shadow mb-4 w-100">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Detalle del concurso</h6>
    </div>
    <div class="card-body">
      <div>
        <div>
          <div class="col-sm-3 mb-3 mb-sm-0">
            <img alt="<%= @contest.name %>" src="<%= image_path(@contest.banner_image_name) %>" class="img-fluid float-left" style="max-width: 100%; height: 300px;"/>
          </div>
        </div>
      </div>
      <div>
        <div class="row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="id-addon">ID</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="id-addon" value="<%= @contest.id %>"/>
            </div>
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="name-addon">Nombre</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="name-addon" value="<%= @contest.name %>"/>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="date_init-addon">Fecha de inicio</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="date_init-addon" value="<%= l @contest.date_init, format: "%d de %B de %Y a la(s) %I:%M %P %Z" %>"/>
            </div>
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="date_end-addon">Fecha de finalización</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="date_end-addon" value="<%= l @contest.date_end, format: "%d de %B de %Y a la(s) %I:%M %P %Z" %>"/>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="prize_amount-addon">Monto del premio</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="prize_amount-addon" value="<%= number_to_currency(@contest.prize_amount) %>"/>
            </div>
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="created_at-addon">Fecha de creación</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="created_at-addon" value="<%= l DateService.get_created_at_COT(@contest.created_at), format: "%d de %B de %Y a la(s) %I:%M %P COT" %>"/>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="contest_text-addon">Texto</span>
              </div>
              <textarea class="form-control text-left bg-gray-100" disabled style=" height: 139px; resize: none;" aria-describedby="contest_text-addon"><%= @contest.contest_text %></textarea>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="recommendations-addon">Recomendaciones</span>
              </div>
              <textarea class="form-control text-left bg-gray-100" disabled style=" height: 139px; resize: none;" aria-describedby="recommendations-addon"><%= @contest.recommendations %></textarea>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="winner-addon">Audio ganador</span>
              </div>
              <input type="text" class="form-control text-right bg-gray-100" disabled aria-describedby="winner-addon" value="<%= get_winner(@contest) %>"/>
            </div>
          </div>
          <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="url-addon">URL</span>
              </div>
              <%= link_to @contest.url, @contest.url, target: '_blank', class: "form-control text-left", "disabled aria-describedby": "url-addon" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="card shadow mb-4 w-100">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Audios</h6>
    </div>
    <div class="card-body">
      <% if !@audios.blank? %>
        <div class="table-responsive">
          <table class="table table-bordered small" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>ID</th>
              <th>Nombres</th>
              <th>Apellidos</th>
              <th>Email</th>
              <th>Observaciones</th>
              <th>Estado</th>
              <th>Fecha de subida</th>
              <th>Extensión original</th>
              <th>Audio original</th>
              <th>Audio procesado</th>
              <th>Seleccionar ganador</th>
            </tr>
            </thead>
            <tbody>
            <% @audios.each do |audio| %>
              <tr>
                <td><%= audio.id %></td>
                <td><%= audio.participant.first_name %></td>
                <td><%= audio.participant.last_name %></td>
                <td><%= audio.participant.email %></td>
                <td><%= audio.observations %></td>
                <td><%= ContestStatusService.get_status_name(audio.status) %></td>
                <td><%= l DateService.get_created_at_COT(audio.created_at), format: "%d de %B de %Y a la(s) %I:%M %P COT" %></td>
                <td><%= File.extname(audio.original_name) %></td>
                <td class="text-right">
                  <audio src="<%= audio_path('original/' + audio.original_name) %>" controls controlsList="nodownload">
                    Tu explorador web no soporta reproducción de audios
                  </audio>
                  <a href="<%= audio_path('original/' + audio.original_name) %>" download="<%= get_nice_download_filename(audio, true) %>">
                    <i class="fas fa-fw fa-file-download"></i>
                    <span>Descargar</span>
                  </a>
                </td>
                <td class="text-right">
                  <% if audio.status.eql?(ContestStatusService.CONVERTED) %>
                    <audio src="<%= audio_path('converted/' + audio.converted_name) %>" type="audio/mpeg" controls controlsList="nodownload">
                      Tu explorador web no soporta reproducción de audios
                    </audio>
                    <a href="<%= audio_path('converted/' + audio.converted_name) %>" download="<%= get_nice_download_filename(audio, false) %>">
                      <i class="fas fa-fw fa-file-download"></i>
                      <span>Descargar</span>
                    </a>
                  <% else %>
                    <p class="text-left"><%= ContestStatusService.get_status_description(audio.status) %></p>
                  <% end %>
                </td>
                <td>
                  <% if @contest.winner_audio_id.to_s == audio.id.to_s %>
                    <strong>Actual ganador</strong>
                  <% else %>
                    <%= form_with url: '/contests/' + @contest.id.to_s + '/winner/' + audio.id.to_s, local: true do |form| %>
                      <%= form.submit '¿Ganador?', class: "btn btn-primary" %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            <tr>
              <td colspan="11">
                <select id="selectOpt" onchange="getAudios()">
                  <% @limits_per_page.each do |limit| %>
                    <% if limit.to_s == @limit.to_s %>
                      <option value="<%= limit %>" selected><%= limit %></option>
                    <% else %>
                      <option value="<%= limit %>"><%= limit %></option>
                    <% end %>
                  <% end %>
                </select>
                &nbsp;
                registros por página
                <nav class="text-right float-right">
                  <ul class="pagination">
                    <% @pages.each do |page| %>
                      <li class="page-item">
                        <% if page.to_s == @current_page.to_s %>
                          <a class="page-link"><%= page %></a>
                        <% else %>
                          <%= link_to page.to_s, '/contests/' + @contest.id.to_s + '?offset=' + ((page - 1) * @limit.to_i).to_s + '&limit=' + @limit.to_s, class: "page-link" %>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </nav>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      <% else %>
        <p class="mb-4">No hay audios registrados para este concurso</p>
      <% end %>
    </div>
  </div>
</div>

<script>
  function getAudios() {
    let myselect = document.getElementById("selectOpt");
    window.location.href = '/contests/' + <%= @contest.id.to_s %> +'?limit='
        + myselect.options[myselect.selectedIndex].value;
  }
</script>