config/routes.rb
Rails.application.routes.draw do
  resources :contests

  root 'welcome#index'

  get     '/',        to: 'welcome#index'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  get     '/logout',  to: 'sessions#delete'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/signin',  to: 'signins#new'
  post    '/signin',  to: 'signins#create'

  get     '/options', to: 'options#index'
  post    '/options', to: 'options#update'

  # This section must be located at the end
  get     '/:url_id', to: 'voices#new'
  get     '/contests/:id/voices', to: 'voices#new_by_id'
  post    '/contests/:id/voices', to: 'voices#create'

  post    '/contests/:id/winner/:winner_audio_id',  to: 'contests#winner'
end

app/controllers/signins_controller.rb
class SigninsController < ApplicationController
  layout 'login'

  def new
    @user = User.new
    @success_message = nil
  end

  def create
    @user = User.new(request_attributes)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to contests_path
    else
      render 'new'
    end
  end

  private def request_attributes
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/signins/new.html.erb
<div class="row">
  <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
  <div class="col-lg-7">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Registrate en SUPER VOICES</h1>
        <% if @user.errors.any? %>
          <div class="error-div">
            <p>
            Hay <%= @user.errors.count %> <%= @user.errors.count.equal?(1) ? "error" : "errores" %>
            en el formulario:
            </p>
            <ul>
              <% @user.errors.messages.each do |attr, msg| %>
                <% msg.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <%= form_with scope: :user, url: signin_path, local: true do |form| %>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <%= form.text_field :first_name, class: "form-control form-control-user", placeholder: "Nombres" %>
          </div>
          <div class="col-sm-6">
            <%= form.text_field :last_name, class: "form-control form-control-user", placeholder: "Apellidos" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.email_field :email, class: "form-control form-control-user", placeholder: "Correo electrónico" %>
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <%= form.password_field :password, class: "form-control form-control-user", placeholder: "Contraseña" %>
          </div>
          <div class="col-sm-6">
            <%= form.password_field :password_confirmation, class: "form-control form-control-user", placeholder: "Confirmar contraseña" %>
          </div>
        </div>
        <%= form.submit 'Registrar', class: "btn btn-primary btn-user btn-block" %>
      <% end %>
      <hr>
      <div class="text-center">
        <%= link_to 'Ya tienes una cuenta ? Haz login !', login_path, class: "small" %>
      </div>
    </div>
  </div>
</div>