config/routes.rb
Rails.application.routes.draw do
  resources :contests

  root 'welcome#index'

  get     '/',        to: 'welcome#index'

  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  get     '/logout',  to: 'sessions#delete'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/signin',  to: 'signins#new'
  post    '/signin',  to: 'signins#create'

  get     '/options', to: 'options#index'
  post    '/options', to: 'options#update'

  # This section must be located at the end
  get     '/:url_id', to: 'voices#new'
  get     '/contests/:id/voices', to: 'voices#new_by_id'
  post    '/contests/:id/voices', to: 'voices#create'

  post    '/contests/:id/winner/:winner_audio_id',  to: 'contests#winner'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUPER VOICES</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Custom fonts for this template-->
  <link rel="shortcut icon" href="<%= image_path('index/images/SUPER_VOICES_ICON.png') %>"/>
  <link href="<%= stylesheet_path('fontawesome-free/css/all.min.css') %>" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400i,700,700i,900|Montserrat:400,700|PT+Serif' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag 'admin/sb-admin-2', media: 'all', 'data-turbolinks-track': 'reload' %>

  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <%= link_to contests_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
      <div class="sidebar-brand">SUPER VOICES</div>
    <% end %>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Concursos
    </div>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <%= link_to contests_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-table"></i>
        <span>Ver concursos</span>
      <% end %>
    </li>
    <li class="nav-item active">
      <%= link_to new_contest_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Registrar concurso</span>
      <% end %>
    </li>
    <li class="nav-item active">
      <%= link_to options_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Opciones del sistema</span>
      <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">Bienvenido <%= @user.first_name + " " + @user.last_name %></span>
              <img class="img-profile rounded-circle" src="https://source.unsplash.com/FTfjMijq-Ws/60x60">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
              </a>
            </div>
          </li>

        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">

        <!-- Content Row -->
        <%= yield %>

      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; SUPER VOICES 2019</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">¿Listo para irte?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Para cerrar la sesión haz clic en el botón "Cerrar sesión"</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
        <%= link_to 'Cerrar sesión', logout_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript -->
<script src="<%= javascript_path('vendor/jquery/jquery.min.js') %>"></script>
<script src="<%= javascript_path('vendor/bootstrap/js/bootstrap.bundle.min.js') %>"></script>

<!-- Core plugin JavaScript -->
<script src="<%= javascript_path('vendor/jquery-easing/jquery.easing.min.js') %>"></script>

<!-- Custom scripts for all pages-->
<script src="<%= javascript_path('js/sb-admin-2.min.js') %>"></script>

<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<script>
  $(function () {
    $('#toggle_1').bootstrapToggle();
  })
  $(function () {
    $('#toggle_2').bootstrapToggle();
  })
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUPER VOICES</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="shortcut icon" href="<%= image_path('index/images/SUPER_VOICES_ICON.png') %>"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <title>SUPER VOICES</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Template by Colorlib"/>
  <meta name="keywords" content="HTML, CSS, JavaScript, PHP"/>
  <meta name="author" content="Colorlib"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link rel="shortcut icon" href="<%= image_path('index/images/SUPER_VOICES_ICON.png') %>"/>
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400i,700,700i,900|Montserrat:400,700|PT+Serif' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/clear.css') %>'/>
  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/common.css') %>'/>
  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/font-awesome.min.css') %>'/>
  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/carouFredSel.css') %>'/>
  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/prettyPhoto.css') %>'/>
  <link rel="stylesheet" type="text/css" href='<%= stylesheet_path('index/css/sm-clean.css') %>'/>

  <%= stylesheet_link_tag 'index/style', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!--[if lt IE 9]>
  <script src='<%= javascript_path('index/js/html5.js') %>'></script>
  <![endif]-->

</head>
<body>

<!-- Preloader Gif -->
<table class="doc-loader">
  <tr>
    <td>
      <img src="<%= image_path('index/images/loading.gif') %>" alt="Cargando..."/>
    </td>
  </tr>
</table>

<!-- Menu -->
<div class="menu-wrapper center-relative">
  <nav id="header-main-menu">
    <div class="mob-menu">MENU</div>
    <ul class="main-menu sm sm-clean">
      <li><a href="#home">Inicio</a></li>
      <li><a href="#services">Servicios</a></li>
      <li><a href="#skills">Ventajas</a></li>
      <li><a href="#about">Nosotros</a></li>
      <li><a href="/signin">Registrate</a></li>
      <li><a href="/login">Inicia sesión</a></li>
    </ul>
  </nav>
</div>

<!-- Home -->
<div id="home" class="section intro-page">
  <div class="block content-1170 center-relative center-text">
    <img class="top-logo" src="<%= image_path('index/images/SUPER_VOICES_LOGO.png') %>"/>
    <br>
    <h1 class="big-title">Encuentra la voz que necesitas</h1>
    <h2 class="title-desc">
      Miles de personas en todo el mundo están grabando por ti<br><br>
      <a href="/signin" class="border-dark btn btn-primary" target="_blank">Registrate aquí!</a>
    </h2>
  </div>
</div>

<!-- Service -->
<div id="services" class="section">
  <div class="block content-1170 center-relative">
    <div class="section-title-holder left">
      <div class="section-num">
        <span>01</span>
      </div>
      <h2 class="entry-title">Servicios</h2>
    </div>
    <div class="section-content-holder right">
      <div class="content-wrapper">
        <script>
          var slider1_speed = "500";
          var slider1_auto = "false";
          var slider1_hover = "true";
        </script>
        <div class="image-slider-wrapper relative service slider1">
          <ul id="slider1" class="image-slider slides">
            <li>
              <div class="service-holder ">
                <img src="<%= image_path('index/demo-images/icon_01.png') %>">
                <div class="service-content-holder">
                  <div class="service-title">CONCURSOS</div>
                  <div class="service-content">
                    Registra tus concursos, busca la voz que siempre has deseado, elige a los
                    ganadores y publica los resultados.<br/>
                  </div>
                </div>
              </div>
              <div class="service-holder ">
                <img src="<%= image_path('index/demo-images/icon_02.png') %>">
                <div class="service-content-holder">
                  <div class="service-title">USUARIOS</div>
                  <div class="service-content">
                    Administra tu empresa con las personas que deseas, asignales permisos y permite
                    que ellos administren tu plataforma.<br/>
                  </div>
                </div>
              </div>
              <div class="service-holder ">
                <img src="<%= image_path('index/demo-images/icon_03.png') %>">
                <div class="service-content-holder">
                  <div class="service-title">WEB</div>
                  <div class="service-content">
                    Accede desde cualquier lugar y en cualquier momento.<br/>
                  </div>
                </div>
              </div>
            </li>
          </ul>
          <div class="clear"></div>
        </div>
      </div>
    </div>
    <div class='clear'></div>
  </div>
</div>

<!-- Skills -->
<div id="skills" class="section">
  <div class="block content-1170 center-relative">
    <div class="section-title-holder right">
      <div class="section-num">
        <span>02</span>
      </div>
      <h2 class="entry-title">Ventajas</h2>
    </div>
    <div class="section-content-holder left">
      <div class="content-wrapper">
        <p>Somos una de las empresas con mayor crecimiento en los últimos años. Aprovecha a los
          miles de usuarios que acceden a nuestra plataforma, todos ellos estarán disponibles para
          participar en los concursos publicados.<br/><br/>
          Nuestros números en último año:</p>
        <br>
        <div class="progress_bar ">
          <div class="progress_bar_field_holder" style="width: 90%;">
            <div class="progress_bar_title" style="color: #55B286">Procesamiento</div>
            <div class="progress_bar_percent_text" style="color: #55B286">90%</div>
            <div class="progress_bar_field_perecent" style="background-color:#32DB8A;"></div>
          </div>
        </div>
        <div class="progress_bar ">
          <div class="progress_bar_field_holder" style="width:80%;">
            <div class="progress_bar_title" style="color: #E3A536">Últimas tecnologías</div>
            <div class="progress_bar_percent_text" style="color: #E3A536">80%</div>
            <div class="progress_bar_field_perecent" style="background-color:#FFBB42;"></div>
          </div>
        </div>
        <div class="progress_bar ">
          <div class="progress_bar_field_holder" style="width:20%;">
            <div class="progress_bar_title" style="color: #B24564">Caidas</div>
            <div class="progress_bar_percent_text" style="color: #B24564">5%</div>
            <div class="progress_bar_field_perecent" style="background-color:#E74C78;"></div>
          </div>
        </div>
        <div class="progress_bar ">
          <div class="progress_bar_field_holder" style="width:85%;">
            <div class="progress_bar_title" style="color: #468ac7">Experiencia de usuario</div>
            <div class="progress_bar_percent_text" style="color: #468ac7">85%</div>
            <div class="progress_bar_field_perecent" style="background-color:#4C9EE7;"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

<!-- About -->
<div id="about" class="section">
  <div class="block content-1170 center-relative">
    <div class="section-title-holder left">
      <div class="section-num">
        <span>03</span>
      </div>
      <h2 class="entry-title">Nosotros</h2>
    </div>
    <div class="section-content-holder right">
      <div class="content-wrapper">
        <div class="content-wrapper">
          Somos una empresa Colombiana, ubicada en la ciudad de Bogotá.<br/><br/>
          Creemos firmemente en brindar los mejores servicios a las personas, hacer su vida mucho
          más facil.<br/><br/>
          Nuestro objetivo es que encuentres la voz que deseas y para eso contamos con los mejores
          ingenieros, profesionales en medios de comunicación y todas las personas trabajando para
          ti.
        </div>
        <div class="clear"></div>
        <br>
      </div>

      <div class="full-width ">
        <script>
          var aboutImage_speed = "500";
          var aboutImage_auto = "false";
          var aboutImage_hover = "true";
        </script>
        <div class="image-slider-wrapper relative img aboutImage">
          <div class="caroufredsel_wrapper">
            <ul id="aboutImage" class="image-slider slides">
              <li><img src="https://source.unsplash.com/yFbyvpEGHFQ/600x400"></li>
              <li><img src="https://source.unsplash.com/73o_FzZ5x-w/600x400"></li>
              <li><img src="https://source.unsplash.com/byW_4p0EKMA/600x400"></li>
            </ul>
          </div>
          <div class="clear"></div>
        </div>

        <script>
          var team1_speed = "500";
          var team1_auto = "false";
          var team1_hover = "true";
        </script>
        <div class="image-slider-wrapper relative team team1">
          <a id="team1_next" class="image_slider_next" href="#"></a>
          <div class="caroufredsel_wrapper">
            <ul id="team1" class="image-slider slides">
              <li>
                <div class="member-content-holder">
                  <h4 class="member-name">Jesus Insuasty</h4>
                  <p class="member-position">Software developer</p>
                  <div class="member-content">
                    Jesus está encargado del diseño y programación del sitio web.<br><br>
                    Es quien administra los servicios de audio y verifica que estén disponibles en
                    el momento en que los usuarios lo necesitan.
                  </div>
                </div>
                <div class="member-image-holder">
                  <img src="https://source.unsplash.com/WZbHIyrtkCI/600x600">
                </div>
                <div class="clear"></div>
              </li>
            </ul>
          </div>
          <div class="clear"></div>
        </div>
      </div>   <!-- end full-width div -->

    </div>
    <div class="clear"></div>
  </div>
</div>

<!-- Footer -->
<footer>
  <div class="footer content-1170 center-relative">
    <ul>
      <li class="copyright-footer">
        © 2018 All rights reserved. | Boxus Template by
        <a href="https://colorlib.com" target="_blank">Colorlib</a>
      </li>
      <li class="social-footer">
        <a href="https://github.com/ISIS4426-Desarrollo-Soluciones-Cloud/Grupo03" target="_blank"><span class="fa fa-github"></span></a>
      </li>
    </ul>
  </div>
</footer>

<!--Load JavaScript-->
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.sticky-kit.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.smartmenus.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.sticky.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.dryMenu.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/isotope.pkgd.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.carouFredSel-6.2.0-packed.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.mousewheel.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.touchSwipe.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.easing.1.3.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/imagesloaded.pkgd.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.prettyPhoto.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/main.js') %>'></script>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUPER VOICES</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Custom fonts for this template-->
  <link rel="shortcut icon" href="<%= image_path('index/images/SUPER_VOICES_ICON.png') %>"/>
  <link href="<%= stylesheet_path('fontawesome-free/css/all.min.css') %>" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400i,700,700i,900|Montserrat:400,700|PT+Serif' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag 'admin/sb-admin-2', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gradient-primary">

<!-- Menu -->
<div class="menu-wrapper center-relative">
  <nav id="header-main-menu">
    <div class="mob-menu">MENU</div>
    <ul class="main-menu sm sm-clean">
      <li><a href="/">Inicio</a></li>
      <li><a href="/signin">Registrate</a></li>
      <li><a href="/login">Inicia sesión</a></li>
    </ul>
  </nav>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src='<%= javascript_path('index/js/jquery.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.sticky-kit.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.smartmenus.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.sticky.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.dryMenu.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/isotope.pkgd.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.carouFredSel-6.2.0-packed.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.mousewheel.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.touchSwipe.min.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.easing.1.3.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/imagesloaded.pkgd.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/jquery.prettyPhoto.js') %>'></script>
<script type='text/javascript' src='<%= javascript_path('index/js/main.js') %>'></script>

</body>
</html>

app/views/layouts/participant.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUPER VOICES</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="shortcut icon" href="<%= image_path('index/images/SUPER_VOICES_ICON.png') %>"/>
  <%= stylesheet_link_tag 'participant', media: 'all', 'data-turbolinks-track': 'reload' %>

  <style>
    .content {
      max-width: 1100px;
      margin: auto;
    }
  </style>
</head>

<body class="content">
<%= yield %>
</body>

<script type='text/javascript' src='<%= javascript_path('index/js/jquery.js') %>'></script>
</html>